version: '3'
services:
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app:cached
      - bundle-volume:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DB_USER: root
      DB_NAME: invoice
      DB_PASSWORD: password
      DB_HOST: db
    tty: true
    stdin_open: true
    networks:
      - invoice-app
  db:
    image: mysql:8
    restart: always
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: invoice
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: "Asia/Jakarta"
    ports:
      - "3306:3306"
    networks:
    - invoice-app

  invoice-adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - '9090:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=db
    networks:
      - invoice-app
    depends_on:
      - db

volumes:
    bundle-volume:
    mysql-volume:

networks:
  invoice-app:
    name: Invoice-app
    driver: bridge