# fly.toml app configuration file generated for rails-invoice-api-app on 2023-08-02T20:12:02+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rails-invoice-api-app"
primary_region = "sin"
console_command = "/rails/bin/rails console"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
